repos:
-
  repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v4.3.0"
  hooks:
  -   id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
  -   id: end-of-file-fixer
  -   id: check-executables-have-shebangs
  -   id: check-yaml
-
  repo: "https://gitlab.com/pycqa/flake8"
  rev: "5.0.4"
  hooks:
    - id: flake8
-
  repo: "https://github.com/d4ilyrun/pre-commit-hooks"
  rev: "v1.0.5"
  hooks:
    - id: apply-nixpkgs-fmt
