-
  id: check-clang-format
  name: Check that all source files follow the clang-format configuration
  language: python
  entry: hooks/clang-format.py
  types_or: [ c, c++, c#, objective-c, java ]
-
  id: apply-clang-format
  name: Apply clang-format configuration to source files
  language: python
  entry: hooks/clang-format.py
  types_or: [ c, c++, c#, objective-c, java ]
  args: [ --apply-fixes ]
-
  id: check-nixpkgs-fmt
  name: Check that all Nix files are formatted correctly
  language: python
  entry: hooks/nixpkgs-fmt.py
  types_or: [ nix ]
-
  id: apply-nixpkgs-fmt
  name: Format all Nix files correctly
  language: python
  entry: hooks/nixpkgs-fmt.py
  types_or: [ nix ]
  args: [ --apply-fixes ]
